YogaClass/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views as mainViews

urlpatterns = [
    path("admin/", admin.site.urls),
    path("item", mainViews.test, name="test"),
    path("", mainViews.index, name="index"),
    path("accounts/", include("users.urls")),
    path("enroll/", include("batches.urls")),
]

handler404 = "YogaClass.views.error_404_view"

users/urls.py
from django.urls import path, include, re_path
from . import views as userViews

urlpatterns = [
    path("logout/", userViews._logout, name="logout"),
    path("profile/", userViews.profile, name="profile"),
    path("login-success/", userViews.login_success, name="login-success"),
    re_path(r"^(?P<state>[a-zA-Z])?", userViews.account, name="account"),
    re_path(r"^.*$", userViews.spechul, name="spechul"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from batches.models import Slots, Month

# Create your models here.
class UserModel(User):
    fullname = models.CharField(max_length=100)
    age = models.IntegerField(null=False)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

    def get_full_name(self):
        return self.fullname

    def __str__(self):
        return self.get_full_name()


class ProfileModel(models.Model):
    user = models.OneToOneField(UserModel, on_delete=models.CASCADE)
    premium = models.BooleanField(default=False)
    batch_slots = models.IntegerField(choices=Slots, default=0)  # 0 for no batch
    batchmonth = models.CharField(choices=Month, max_length=3, default="N/A")
    batch_fee = models.IntegerField(default=500)

    def __str__(self):
        return self.user.username

users/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import password_validation
from .models import UserModel, ProfileModel
from django import forms


class UsersForm(UserCreationForm):
    fullname = forms.CharField(
        max_length=100,
        required=True,
        strip=True,
        widget=forms.TextInput(attrs={"placeholder": "Full Name"}),
    )
    age = forms.IntegerField(
        required=True,
        min_value=18,
        max_value=85,
        widget=forms.TextInput(attrs={"placeholder": "Age (18-85)"}),
    )
    username = forms.CharField(
        max_length=100,
        required=True,
        strip=True,
        widget=forms.TextInput(attrs={"placeholder": "Username"}),
    )
    email = forms.EmailField(
        max_length=100,
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "Email"}),
    )
    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password", "placeholder": "Password"}
        ),
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password", "placeholder": "Repeat Password"}
        ),
        strip=False,
        help_text="Enter the same password as before, for verification.",
    )

    class Meta:
        model = UserModel
        fields = ("fullname", "age", "username", "email", "password1", "password2")


class AuthForm(AuthenticationForm):
    username = forms.CharField(
        max_length=100,
        required=True,
        strip=True,
        widget=forms.TextInput(attrs={"placeholder": "Username"}),
    )
    password = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "new-password", "placeholder": "Password"}
        ),
    )

    class Meta:
        model = UserModel
        fields = ("username", "password")


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = UserModel
        fields = ["username", "email"]

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from asgiref.sync import sync_to_async
from .forms import UsersForm, AuthForm, UserUpdateForm
from asyncio import sleep


def account(request, **kwargs):
    if request.user.is_authenticated:
        return redirect("enroll")
    if kwargs.get("state") is not None:
        state = kwargs.get("state")
    else:
        state = request.GET.get("state", "login")
    print(messages.get_messages(request))
    print(f"state: {state}", request.POST)
    print()
    if request.method == "POST":
        if request.POST.get("age") is None:
            state = "login"
        else:
            state = "register"
    if state == "register":
        if request.method == "POST":
            form = UsersForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Your account was created successfully.")
                return redirect("account")
            else:
                messages.error(request, form.errors.as_text())
        else:
            form = UsersForm()
    elif state == "login":
        print("login")
        if request.method == "POST":
            form = AuthForm(request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get("username")
                password = form.cleaned_data.get("password")
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(
                        request, f"Your login was successful, {user.get_username()}."
                    )
                    return redirect("enroll")
                else:
                    messages.error(request, "Invalid username or password.")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            form = AuthForm()
    else:
        return render(request, "404.html")
    context = {"form": form, "title": state.capitalize()}
    print(form.fields)
    url = f"/account?state={state}"
    request.session["url"] = url
    return render(request, "register.html", context=context)


def _logout(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("account")


@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, f"Your account has been updated!")
            return redirect("profile")
    else:
        u_form = UserUpdateForm(instance=request.user)

    context = {"u_form": u_form, "title": "Profile"}

    return render(request, "users/profile.html", context)


def spechul(request):
    if request.user.is_authenticated:
        return redirect("enroll")
    return render(request, "404.html")


async def login_success(request, *args, **kwargs):
    render(request, "login-success.html")
    await sleep(5)
    return redirect("enroll")

templates/users/login_success.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>Your Login was successful;<br/> We'll take you to the enrollment section!</p>
      </div>
    </body>
</html>

templates/users/logout.html
{% extends "base_nav.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'account' %}">Log In Again</a> Or <a href="{% url 'index' %}">Return to Home Page</a>
        </small> 
    </div>
{% endblock content %}

templates/users/profile.html
{% extends 'base_nav.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block more_css %}
<link rel="stylesheet" href="{% static 'css/users.css' %}" />
{% endblock %}
{% block content %}
<div class="container">
    <div class='thecontainer'>
        <div class='content-section' style="max-height: 312px">
            <div class="media">
                <img class="rounded-circle account-img" src="https://img.freepik.com/premium-vector/yoga-logo-icon-line-outline-monoline-style_7688-1317.jpg?size=312">
                <div class="media-body">
                <h2 class="account-heading custom" style="color:white; margin-bottom: 15px; position:relactive">{{ user.username }}</h2>
                <p class="custom" style="color:white">{{ user.email }}</p>
                <br>
                </div>
            </div>
            <form method="POST">
                {% csrf_token %}
                <div class='minh'>
                <fieldset class="form-group">
                    <legend class='border-bottom-mb-4'>Profile Info</legend>
                    {{ u_form|crispy }}
                </feldset>
                <div class="form-group">
                    <button type="submit" class="customButt">Update</button> <strong><h5><a href='{% url 'enroll' %}'>Click here to enroll</a></h5></strong>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'base_nav.html' %}
{% load static %}
{% block more_css %}
 <link rel="stylesheet" href="{% static 'css/users.css' %}">
{% endblock %}
{% block more_js %}
    <script src="{% static 'js/users.js' %}"></script>
{% endblock %}
{% block content %}
<div class="container">
	<div class='thecontainer' id="container">
		<div class="form-container sign-up-container">
			<form method="POST">
				{% csrf_token %}
				<h1>Create Account</h1>
				<div class="social-container">
					<a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
					<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
					<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
				</div>
				<span>or use your email for registration</span>
				{% if messages %}
					{% for message in messages %}
						{% if message.tags == 'error' %}
							<div class="alert alert-danger" role="alert">
								{{ message }}
							</div>
							{% else %}
							<div class="alert alert-success" role="alert">
								{{ message }}
							</div>
							{% endif %}
					{% endfor %}
				{% endif %}
				<input type="text" name="fullname" placeholder="Full Name" maxlength="100" required id="id_fullname">
				<input type="text" name="age" placeholder="Age (18-85)" required id="id_age">
				<input type="text" name="username" placeholder="Username" maxlength="100" autofocus required id="id_username">
				<input type="text" name="email" placeholder="Email" maxlength="100" required id="id_email">
				<input type="password" name="password1" autocomplete="new-password" placeholder="Password" required id="id_password1">
				<input type="password" name="password2" autocomplete="new-password" placeholder="Repeat Password" required id="id_password2">
				{% if not messages %}
					<br>
				{% endif %}
				<button type='submit'>Sign Up</button>
			</form>
		</div>
		<div class="form-container sign-in-container">
			<form method="POST">
				{% csrf_token %}
				<h1>Sign In</h1>
				<div class="social-container">
					<a href="#" class="social"><i class="fab fa-facebook-f"></i></a>
					<a href="#" class="social"><i class="fab fa-google-plus-g"></i></a>
					<a href="#" class="social"><i class="fab fa-linkedin-in"></i></a>
				</div>
				<span>or use your account</span>
				{% if messages %}
					{% for message in messages %}
						{% if message.tags == 'error' %}
							<div class="alert alert-danger" role="alert">
								{{ message }}
							</div>
							{% else %}
							<div class="alert alert-success" role="alert">
								{{ message }}
							</div>
							{% endif %}
					{% endfor %}
				{% endif %}
				<input type="text" name="username" placeholder="Username" maxlength="150" required id="id_username">
				<input type="password" name="password" autocomplete="new-password" placeholder="Password" required id="id_password">
				{% comment %} {{ form }} {% endcomment %}
				<a href="#">Forgot your password?</a>
				<button type='submit'>Sign In</button>
			</form>
		</div>
		<div class="overlay-container">
			<div class="overlay">
				<div class="overlay-panel overlay-left">
					<h1>Welcome Back!</h1>
					<p>To book a Yoga Session - Please Sign in!</p>
					<button class="ghost" id="signIn" onclick='signinbutt()'>Sign In</button>
				</div>
				<div class="overlay-panel overlay-right">
					<h1>Hello, Friend!</h1>
					<p>Enter your personal details and start booking your Yoga Classes!</p>
					<button class="ghost" id="signUp" onclick='signupbutt()'>Sign Up</button>
				</div>
			</div>
		</div>
	</div>
</div>
	{% comment %} <script>
		const signUpButton = document.getElementById('signUp');
		const signInButton = document.getElementById('signIn');
		const container = document.getElementById('container');

		signUpButton.addEventListener('click', () => {
			container.classList.add("right-panel-active");
		});

		signInButton.addEventListener('click', () => {
			container.classList.remove("right-panel-active");
		});
	</script> {% endcomment %}
{% endblock %}